### ISSUE TITLE
Redner: Vortrag hinzufügen

### ISSUE THREAD

**Issue by thomasramm** [thomasramm/Vortragsmanager#41]
Beim Stammdatenanlegen (Neue Redner per Hand unter einer Versammlung anlegen) wird beim Auswählen eines einzelnen Vortrags aus der Combobox zwar der Vortrag angezeigt. Doch wenn ich auf den ausgewählten Vortrag klicke, um in einzutragen, klappt die Eingabe Maske zu ohne den Vortrag zu übernehmen.

**Comment by thomasramm** [comment]
Der Fehler ist bei mir nicht reproduzierbar.
Ich kann den Vortrag per Tastatur selektieren (eingeben der Vortragsnummer) oder mit der Maus auswählen. in beiden Fällen ist er in der ComboBox übernommen, danach auf "speichern" klicken

**Comment by joerg007** [comment]
Ich habe es gerade noch einmal versucht. Geht jetzt, wie du es beschrieben hast. War wohl nur in der älteren Version vorhanden. (0.9.4)
Ich würde mir aber noch wünschen, sowohl bei der Auswahl aus der Combobox für einzelne Vorträge, als auch bei der Kommagetrennten Eingabe per Enter bestätigen zu können.

**Comment by thomasramm** [comment]
bei beiden Möglichkeiten einen Vortrag hinzuzufügen (DropDown-Liste oder Kommagetrennte Liste) kann man den Vortrag nun mit Enter speichern.
