### ISSUE TITLE
Vortragsplanung anzeigen

### ISSUE THREAD

**Issue by thomasramm** [thomasramm/Vortragsmanager#44]
Vorträge nach Nummer suchen lassen und mir alle Redner anzeigen lassen, die diesen Vortrag halten.

**Comment by thomasramm** [comment]
Dies als Excel-Liste ausgeben, oder erwartest du eher das du einen Redner dann dafür "Anfragen" kannst.
An welcher Stelle würdest du diese Funktion erwarten?

**Comment by joerg007** [comment]
Ich könnte mir das unter der Rubrik "Redner suchen" vorstellen. Wenn ich meine Vortragsplanung fülle, suche ich hauptsächlich nach Vorträgen, die noch nie bzw. schon lange nicht mehr gehalten wurden. Dazu schaue ich mir die Liste "gehörte Vorträge" an, wann die Themen das letzte mal gehalten wurden und suche dann nach der Vortragsnr. Wenn ich dann den richtigen Redner gefunden habe, würde ich hieraus eine Anfrage starten wollen.

**Comment by thomasramm** [comment]
Hallo,
ich habe das jetzt bei Redner Suchen eingebaut. 
Neben den Filtern gibt es nun einen weiteren Filter auf Vortragsnummern.
Die Liste wird automatisch gefiltert durch die Checkboxen 
- "Vorträge ausblenden, die bereits eingeplant sind" und 
- "Vorträge ausblenden, die in den letzten 12 Monaten gehalten wurden"
per Default sind immer alle Vorträge gewählt. In der DropDown-Liste wird die Vortragsnummer. das Vortragsthema und das Datum angezeigt an dem dieser Vortrag zuletzt gehört wurde.
Die Liste kann per Tastatur nach Vortragsnummer durchsucht werden.

Dazu gibt es einen neuen Button unter den Filtern "Redner suchen" der die Liste rechts füllt/aktualisiert.

Lange nicht gehörte Vorträge kann man also sowohl über die Excel-Liste, als auch über diesen Filter heraussuchen.
