### ISSUE TITLE
Report gehörte Vorträge

### ISSUE THREAD

**Issue by thomasramm** [thomasramm/Vortragsmanager#45]
Liste mit gehörten Vorträgen ausgeben lassen, ähnlich Vortragsportal (Danach habe ich für die Zukunft gesucht, welche Themen schon lange nicht mehr oder noch gar nicht gehalten wurden)

**Comment by thomasramm** [comment]
Ich habe die Liste "Vortragsthemen" um die Spalte "zuletzt gehört" erweitert.
Ist es das, was du benötigst? 
Commit #76560c4

**Comment by joerg007** [comment]
Ich denke das ist es. Danke dir.
