### ISSUE TITLE
Lied-Nr. + alternatives Lied zu einem Vortrag pro Redner pro Vortrag

### ISSUE THREAD

**Issue by joerg007** [thomasramm/Vortragsmanager#61]
**Hat dein Funktionswunsch mit einem Problem zu tun? Bitte Beschreibe es.**
Es wäre praktisch, wenn zu den Vorträgen der einzlnen Redner das gewählte Lied einzutragen wäre., da einige Koorinatoren diese Info schon gleich mitliefern. Dazu ein alternatives Lied, falls das Lied z.B. schon beim WT-Studium vor kommt.

**Beschreibe die Lösung die du dir vorstellst**
Ich würde mir vorstellen, das bei jedem Redner zu jeder Vortragsnr. zwei Lieder einzutragen sind. mit 1. und 2. 

**Beschreibe Alternativen die du dir überlegt hast**
Eine Alternative wäre zu jedem Redner ein Bemerkungsfeld mit Freitext.

**Sonstiges**
Alle Informationen die deiner Meinung nach wichtig sind, damit ich die Idee oder Verbesserung verstehen kann.

**Comment by thomasramm** [comment]
Funktion ist fertig, muss noch getestet werden.

**Comment by thomasramm** [comment]
Es wäre schön wenn du die neuen Funktion testen würdest und mir dein Feedback gibst.
Dazu bitte deine vortragsmanager.sqlite3 Datei sichern, die neue Version starten und testen, danach die Versammlungsdatei löschen und die gesicherte Datei wieder zurückspielen.
Die aktuelle Testversion kann über diesen Link heruntergeladen werden: [Google Drive](https://drive.google.com/file/d/1oR9N8NkruVNfqp_hNA7fTh5S2epb94nf/view?usp=sharing)
